# This is provided purely for testing purposes.

version: '2'
services:
    zookeeper:
      image: analytics/zookeeper
      container_name: zookeeper
      ports:
        - "2181:2181"

    postgres:
      image: analytics/postgres-hive
      container_name: postgres
      ports:
        - "5432:5432"

    namenode:
      image: analytics/hadoop-namenode
      container_name: namenode
      volumes:
        - ~/datascience-cluster/hadoop/namenode:/hadoop/dfs/name
      environment:
        - CLUSTER_NAME=test
      env_file:
        - ./hadoop.env
      ports:
        - "50070:50070"
        - "8020:8020"

    datanode1:
      image: analytics/hadoop-datanode
      container_name: datanode1
      depends_on:
          - namenode
      volumes:
        - ~/datascience-cluster/hadoop/datanode1:/hadoop/dfs/data
      env_file:
        - ./hadoop.env


    hive:
      image: analytics/hadoop-hive
      depends_on:
        - zookeeper
        - postgres
      container_name: hive
      environment:
        - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
        - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      env_file:
        - ./hadoop.env
      ports:
        - "10000:10000"
        - "10002:10002"
